name: WZXY_DailyReport

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

  schedule:
  # Github Action 使用世界标准时间（UTC），北京时间（UTC+8）转换为世界标准时需要减去8小时
    - cron:  '30 23 * * *' # 默认在每天 UTC 23:30 （北京时间 7:30）执行

jobs:
  USER_01:
    runs-on: ubuntu-latest
    environment: WZXY_CONFIG_01 # 填写需要使用的用户配置对应的环境,请自行根据实际情况修改
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Import cache
      uses: actions/cache@v2
      with:
        path: .cache
        key: ${{ secrets.CACHE_NAME }}-${{ github.run_id }}
        restore-keys: ${{ secrets.CACHE_NAME }}-
    - name: Run script
      env:
        DD_BOT_ACCESS_TOKEN: ${{secrets.DD_BOT_ACCESS_TOKEN}}
        DD_BOT_SECRET: ${{secrets.DD_BOT_SECRET}}
        SCT_KEY: ${{secrets.SCT_KEY}}
        BARK_TOKEN: ${{secrets.BARK_TOKEN}}
        PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
        MIAO_CODE: ${{secrets.MIAO_CODE}}
        TG_TOKEN: ${{secrets.TG_TOKEN}}
        TG_CHATID: ${{secrets.TG_CHATID}}
        WZXY_USERNAME: ${{secrets.USERNAME}}
        WZXY_PASSWORD: ${{secrets.PASSWORD}}
        WZXY_TEMPERATURE: ${{secrets.TEMPERATURE}}
        WZXY_LATITUDE: ${{secrets.LATITUDE}}
        WZXY_LONGITUDE: ${{secrets.LONGITUDE}}
        WZXY_COUNTRY: ${{secrets.COUNTRY}}
        WZXY_CITY: ${{secrets.CITY}}
        WZXY_DISTRICT: ${{secrets.DISTRICT}}
        WZXY_PROVINCE: ${{secrets.PROVINCE}}
        WZXY_TOWNSHIP: ${{secrets.TOWNSHIP}}
        WZXY_STREET: ${{secrets.STREET}}
        WZXY_MYAREA: ${{secrets.MYAREA}}
        WZXY_AREACODE: ${{secrets.AREACODE}}
        WZXY_TOWNCODE: ${{secrets.TOWNCODE}}
        WZXY_CITYCODE: ${{secrets.CITYCODE}}
      run: python wzxy-dailyreport.py
  
  ## 多账户配置示例，请复制下面的代码后取消注释再修改，粘贴时注意缩进
  # USER_02:    ## Jobs名，注意修改序号
  #   runs-on: ubuntu-latest
  #   environment:           ## 填写需要使用的用户配置对应的环境,请自行根据实际情况修改
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.9
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.9
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #   - name: Import cache
  #     uses: actions/cache@v2
  #     with:
  #       path: .cache
  #       key: ${{ secrets.CACHE_NAME }}-${{ github.run_id }}
  #       restore-keys: ${{ secrets.CACHE_NAME }}-
  #   - name: Run script
  #     env:
  #       DD_BOT_ACCESS_TOKEN: ${{secrets.DD_BOT_ACCESS_TOKEN}}
  #       DD_BOT_SECRET: ${{secrets.DD_BOT_SECRET}}
  #       SCT_KEY: ${{secrets.SCT_KEY}}
  #       BARK_TOKEN: ${{secrets.BARK_TOKEN}}
  #       PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
  #       MIAO_CODE: ${{secrets.MIAO_CODE}}
  #       TG_TOKEN: ${{secrets.TG_TOKEN}}
  #       TG_CHATID: ${{secrets.TG_CHATID}}
  #       WZXY_USERNAME: ${{secrets.USERNAME}}
  #       WZXY_PASSWORD: ${{secrets.PASSWORD}}
  #       WZXY_TEMPERATURE: ${{secrets.TEMPERATURE}}
  #       WZXY_LATITUDE: ${{secrets.LATITUDE}}
  #       WZXY_LONGITUDE: ${{secrets.LONGITUDE}}
  #       WZXY_COUNTRY: ${{secrets.COUNTRY}}
  #       WZXY_CITY: ${{secrets.CITY}}
  #       WZXY_DISTRICT: ${{secrets.DISTRICT}}
  #       WZXY_PROVINCE: ${{secrets.PROVINCE}}
  #       WZXY_TOWNSHIP: ${{secrets.TOWNSHIP}}
  #       WZXY_STREET: ${{secrets.STREET}}
  #       WZXY_MYAREA: ${{secrets.MYAREA}}
  #       WZXY_AREACODE: ${{secrets.AREACODE}}
  #       WZXY_TOWNCODE: ${{secrets.TOWNCODE}}
  #       WZXY_CITY_CODE: ${{secrets.CITY_CODE}}
  #     run: python wzxy-dailyreport.py      
