name: WZXY_DailyReport

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

  schedule:
  # Github Action 使用世界标准时间（UTC），北京时间（UTC+8）转换为世界标准时需要减去8小时
    - cron:  '30 12,23 * * *' # 默认在每天 UTC 12:30 和 23:30 （北京时间 20:30 和 7:30）执行



jobs:
  WZXY_DailyReport:

    runs-on: ubuntu-latest
    environment: WZXY_POSITION_DR

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Import cache
      uses: actions/cache@v2
      with:
        path: .cache
        key: ${{ secrets.CACHE_NAME }}-${{ github.run_id }}
        restore-keys: ${{ secrets.CACHE_NAME }}-
    - name: Run script
      env:
        PUSH_TOKEN: ${{secrets.PUSH_TOKEN}}
        WZXY_USERNAME: ${{secrets.USERNAME}}
        WZXY_PASSWORD: ${{secrets.PASSWORD}}
        WZXY_TEMPERATURE: ${{secrets.TEMPERATURE}}
        WZXY_LATITUDE: ${{secrets.LATITUDE}}
        WZXY_LONGITUDE: ${{secrets.LONGITUDE}}
        WZXY_COUNTRY: ${{secrets.COUNTRY}}
        WZXY_CITY: ${{secrets.CITY}}
        WZXY_DISTRICT: ${{secrets.DISTRICT}}
        WZXY_PROVINCE: ${{secrets.PROVINCE}}
        WZXY_TOWNSHIP: ${{secrets.TOWNSHIP}}
        WZXY_STREET: ${{secrets.STREET}}
      run: python wzxy-dailyreport.py
      